package Ventanas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Filtros.Filtro;
import Filtros.FiltroPalabraLarga;
import Formatos.Formato;
import Formatos.FormatoCursiva;
import editor.Seccion;
import editor.Visitor;

/**
 *
 * @author adrianguerrero
 */
public class PalabrasLargas extends javax.swing.JFrame {

    private int cantidad;
    private Visitor v;
    private Seccion seccion;
    private Formato formato;
    private javax.swing.JEditorPane jEditorPane1;
    
    /**
     * Creates new form PalabrasLargas
     */
    public PalabrasLargas(Seccion seccion,javax.swing.JEditorPane jEditorPane1, Formato formato) {
        initComponents();
        this.seccion=seccion;
        this.jEditorPane1=jEditorPane1;
        this.formato=formato;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        cantidadLetras = new javax.swing.JTextPane();
        Aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("Ingrese la cantidad de letras: ");

        jScrollPane1.setViewportView(cantidadLetras);

        Aceptar.setText("Aceptar");
        Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Aceptar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Aceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarMouseClicked
        Filtro filtro = new FiltroPalabraLarga(Integer.parseInt(cantidadLetras.getText()));
        
        Visitor v = new Visitor(filtro,null,null,null,formato,null,null,null);
        Seccion nuevaSeccion = (Seccion) seccion.copia();
       
       nuevaSeccion.aceptar(v);
       String filtrado = nuevaSeccion.listar();
       jEditorPane1.setContentType("text/plain");
       jEditorPane1.setText(filtrado);
       dispose();
    }//GEN-LAST:event_AceptarMouseClicked

    /**
     * @param args the command line arguments
     */
    

    public int getCantidadLetras (){
        return cantidad;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JTextPane cantidadLetras;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}



